export { default as About } from './About/About'
export { default as Home } from './Home/Home'
export { default as Contact } from './Contact/Contact'
export { default as News } from './News/News'
export { default as OEM } from './OEM/OEM'
export { default as Products } from './Products/Products'
export { default as Clients } from './Clients/Clients'